#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define PADDLE_WIDTH 5
#define PADDLE_HEIGHT 50
#define PADDLE_HORIZONTAL_PADDING ((WINDOW_WIDTH) / (10))
#define PADDLE_VELOCITY 30

#define BALL_RADIUS 7
#define BALL_VELOCITY 7

#define WINDOW_WIDTH 640
#define WINDOW_HEIGHT 480

#endif // CONSTANTS_H_
